### ISSUE TITLE
(suggestion) Adobe Creative Cloud liseence request

### ISSUE THREAD

**Issue by SmallestMax** [breqdev/nuisance#9]
This webpage is so hard to find despite an entire college of people who need it all the time. almost every single CAMD student needs access to the creative cloud so it would be super cool if it was easy to find. 

the form for the request is [here](https://northeastern.service-now.com/tech?id=sc_cat_item&sys_id=8f5ddc50dbfa5410a37cd206ca961953)

**Comment by breqdev** [comment]
Should be up on https://nuisance.breq.dev/ :+1:
